#!/usr/bin/env bash

die()
{
	local _ret=$2
	test -n "$_ret" || _ret=1
	test "$_PRINT_HELP" = yes && print_help >&2
	echo "$1" >&2
	exit ${_ret}
}


begins_with_short_option()
{
	local first_option all_short_options='h'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_connector="off"


print_help()
{
	printf '%s\n' "Stop all Glowing Bear and TranSMART components using docker-compose."
	printf 'Usage: %s [--(no-)connector] [-h|--help]\n' "$0"
	printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			--no-connector|--connector)
				_arg_connector="on"
				test "${1:0:5}" = "--no-" && _arg_connector="off"
				;;
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
				;;
		esac
		shift
	done
}

parse_commandline "$@"

docker-compose -f docker-compose.yml -f keycloak.yml -f glowingbear-ssl-proxy.yml $([[ $_arg_connector = "on" ]] && echo '-f connector.yml') down
